// Code generated by kun; DO NOT EDIT.
// github.com/RussellLuo/kun

package eventsvc

import (
	"context"

	"github.com/RussellLuo/kun/pkg/eventcodec"
	"github.com/RussellLuo/kun/pkg/eventpubsub"
)

func NewEventHandler(svc Service, codecs eventcodec.Codecs) eventpubsub.Handler {
	var codec eventcodec.Codec
	handlerSet := eventpubsub.NewHandlerSet()

	codec = codecs.EncodeDecoder("EventCreated")
	handlerSet.Add("created", eventpubsub.NewSubscriber(
		MakeEndpointOfEventCreated(svc),
		decodeEventCreatedInput(codec),
	))

	return handlerSet
}

func decodeEventCreatedInput(codec eventcodec.Codec) eventpubsub.DecodeInputFunc {
	return func(_ context.Context, event eventpubsub.Event) (interface{}, error) {
		var input EventCreatedRequest

		if err := codec.Decode(event.Data(), &input); err != nil {
			return nil, err
		}

		return &input, nil
	}
}
