// Code generated by kun; DO NOT EDIT.
// github.com/RussellLuo/kun

package cronsvc

import (
	"github.com/RussellLuo/micron"
)

func NewCronJobs(svc Service) []micron.Job {
	return []micron.Job{
		{
			Name:    "send_email",
			Expr:    "@every 5s",
			Handler: svc.SendEmail,
		},
	}
}
