// Code generated by kun; DO NOT EDIT.
// github.com/RussellLuo/kun

package cronsvc

import (
	"context"

	"github.com/go-kit/kit/endpoint"
)

// MakeEndpointOfSendEmail creates the endpoint for s.SendEmail.
func MakeEndpointOfSendEmail(s Service) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (interface{}, error) {
		s.SendEmail()
		return nil, nil
	}
}
