// Code generated by kun; DO NOT EDIT.
// github.com/RussellLuo/kun

package fileupload

import (
	"context"

	"github.com/RussellLuo/kun/pkg/httpcodec"
	"github.com/RussellLuo/kun/pkg/httpoption"
	"github.com/RussellLuo/validating/v3"
	"github.com/go-kit/kit/endpoint"
)

type UploadRequest struct {
	File *httpcodec.FormFile `json:"file"`
}

// ValidateUploadRequest creates a validator for UploadRequest.
func ValidateUploadRequest(newSchema func(*UploadRequest) validating.Schema) httpoption.Validator {
	return httpoption.FuncValidator(func(value interface{}) error {
		req := value.(*UploadRequest)
		return httpoption.Validate(newSchema(req))
	})
}

type UploadResponse struct {
	Err error `json:"-"`
}

func (r *UploadResponse) Body() interface{} { return r }

// Failed implements endpoint.Failer.
func (r *UploadResponse) Failed() error { return r.Err }

// MakeEndpointOfUpload creates the endpoint for s.Upload.
func MakeEndpointOfUpload(s Service) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (interface{}, error) {
		req := request.(*UploadRequest)
		err := s.Upload(
			ctx,
			req.File,
		)
		return &UploadResponse{
			Err: err,
		}, nil
	}
}
